language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate RAILS_ENV=test
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  app: acebook-luckerberg
  on:
    repo: Hyan18/acebook-luckerberg
    branch: add-test-coverage
  run:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  api_key:
    secure: SqqLTKzXmU8Isve3kLAL9T87td4AYB7BAQHDv8j6OwKPxmKwIC53APUrBm5pRfFHG3ECAxrtD4rW54UNnmQGgM/oqJT5be4y7VRSD7GGAs927kO4MOhpUki0yGo4/GsTQYQNnqO0+61dsZyZFqVa6EIS/cK0ejLr05gEVKn+w8L5e7CI6p+v2XPvqg7T3bJyacOsifBCckqsjsLIbBmla7SlJ+ChRCKkeQIH66fWMv2KHgV46HdezdO9cnyWiRmzcF7qVbyJucym7ctoV/eUovBXEsqqCmrC7euj6lmZ7SSL5zIptliK0MdL8tvpoAixGY+XtsUMrM3GCLsuIa6VlFDKUvucpvMpHa/KMlkzUnJWaGVYcUKUKi7PWo/t8kL9aOtYB78r4rWdSiHx/LUquwR2uYznuYtfLXzs0bAaspktebfs7LMB/0g+bgv9I8qNSykOpFfCIDmppbt+uASGUXAKMKsxhsEmtX8jQXxVaUWCoW2RzjGRHo/lB/X/k/4zrSrowNQFXKqW0kBvao/hB1gGgK9usZZzQCNiCkqbGfzb/XHYMpRl5GwAE+BGiX1+9h5LOIDHRzmk3wSbfZPdFHOshUkDskrhV1BLTL/YSMlTAb4JCSWefypBWPWnzAozlxycUyREQBkiReCfst0rQpgIl9RHV2HNy5xOGm/OTzk=
