language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate RAILS_ENV=test
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  app: acebook-luckerberg
  on:
    repo: Hyan18/acebook-luckerberg
    branch: add-test-coverage
  run:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  api_key:
    secure: fc8348c8-6770-447d-96c7-26909137b417