language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate RAILS_ENV=test
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  app: acebook-luckerberg
  on:
    repo: Hyan18/acebook-luckerberg
    branch: add-test-coverage
  run:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  api_key:
    secure: ckUmDpi7m7wYzya+oCDmKKj45kup9Voy/De3iGuFg+cJciuhfO3MLI8HqNNpfUISlKQQj8Y7ZnpbD4sKg0K91RdklW1NV/psjolkYwa4RWk1oLVT1bD0pWSMhlJK1r3I/Bs3SMR0MAMxUKuV8Ts6bmNSW4phCFY6ow81cr0o5Ac7QwbriGtQx6LyonbpNWwSCZF9JdkEzqvnvYfk/dOYNGlp72OK0lSfIF5QeJTooLX1i6g2kdGet7P7SOVQHhHj2l8wZKwuQj1nlUvKJ5wC1G81aSIRLhry8Pwz6jqYXgCoTWW8lFGwZYDHD2Oy7T/+gBfwH69pBgdQjPUe7Xq+ujfCvLMLaqHmJvHnoq0cXpKMGEOY3/9JkeD+sTkZoF2XDmT95OOBvN2JlnjD2KEzuvaJJq/TXpPhhD6+ml3MSkDxSz1MNXRRQ0h1Lc93HPNxe5bvBzcKKDAwKYF6S5H+i4QmMvANo/0BavWXDBtGg4j5hZBAZ1RW0H9OWkiQEfdE/Ob0xpkaLPfkXGkz6d8FM0bSx+7x0VXBO685Aas6p9uqPQAG2qbzlMiRaFlH3YSQ9r75bhTwk5Zd7c3eqcIAOnR14NPxA0PiWArHpug4+rFIXIN+2X94Jf9ZnzeCmcGXtgbLy/k2ma6qiu8IMnjEFCHPpAS8/rif9mOtVp1qTK0=
