language: ruby
rvm:
 - 2.5

services:
  - postgresql


before_script:
  - psql -c 'create database pgapp_test;' -U postgres
  -bundle exec rails db:migrate RAILS_ENV=test

script:
  -bundle exec rubocop -c .rubocop.yml .
