language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate RAILS_ENV=test
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  app: acebook-november2019
  on:
    repo: Hyan18/acebook-luckerberg
    branch: add-test-coverage
  run:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  api_key:
    secure: K5U+uyw9Xnj+ahLNyMdvh4acIHRybHw+F4RTYjDypNyjnLz+lL28PAeRDxSfan4455kdkXNZUgUsy6e6qfVZ4fNoRohduBb4be82gXDhAZBLfSnXOfwyo9XcZqtmrMR1YRiQylMbvwccV0Hft0o7seXZVP46ip1AdLIuPmn1aw6BrA8s3Bfm05A+Y/fcByhYJ+m/WcPlIK92eb8mLg+ZoSTsDm6imjj+/8YFJMZdVskNUul59ffRop3FMfYliIU1+egRn5/xyl9yKvdKZXJ6FStlHAB7A/NMVwMB2VEeSKrc2ImNnUHOQiQJFVjP7oprmq42hWgGP/VbtgpDY1UNPFsuLnX16e1CEUXB3nvFyfM8QWeVprXkhdw8sep+86eSEDRwU47t+dmcFnhnbbN46dkVhQ6J3KBiLtGkZvYu0HunRUIRrsPpoFKTCDJA+p2SHEAft3hjv7y1hpGTfYKW7vpXsCeYnrj9UqA6/84Loe7VnmkD0KTCALevfZvhiT/tt2kOxBjeANKJdO3KCt23uRsP+8g3JWcN/yK7e2477ZVlNdtgRK0FrL/c6RcNXU0DxI5eGNTZ7+rMQXjnQHepyIQZnwJjWSDmQGq0QP6vrU+Tk8b783MdcxpK607IJbzJ3r4Q6EfJ1rxV2qPYH0uuC2ZjxL6hAATJlhDkHKrk1K0=
